# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0fd61b18be686246160bc14ab9026b0bc57136e0db73d1ebacb59a82b5108dcfcbcaa851480a293ec37b908815d0c580cf14985893c28c0774895ef583da806

test:
  secret_key_base: 51ad39e26440a84752b4a7c0b190ad498e404d50cb0df025b6a7fcc8632f29eb9e95de9865fd32441aef2b9ac9e47b6fa30b52be3610b87887dd786397de4609

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
